/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Main;

import Elements.table.TableCustom;
import LoginAndSignUp.SignUpPage;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class BookList extends javax.swing.JInternalFrame {

    /**
     * Creates new form IssueBook
     */
    public BookList() {
        Connect();
        initComponents();
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        this.setBorder(BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI panel = (BasicInternalFrameUI) this.getUI();
        panel.setNorthPane(null);
        listbooks();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet Rs;
    Statement st;

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://sql12.freesqldatabase.com/sql12711840", "sql12711840", "P4ylqiF7WZ");

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);

        }
    }
    
     public void listbooks(){
        DefaultTableModel dt =  (DefaultTableModel) BookListTable.getModel();
          
         dt.setRowCount(0);
        try{ 
            st = con.createStatement();
            
            String query = "SELECT * FROM Book_List";
            
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                   
                Vector v = new Vector();
              
              v.add(rs.getString("Book_Title")); 
              v.add(rs.getString("Book_Author"));
              v.add(rs.getString("Publish_Date"));

              dt.addRow(v);
            }  
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        curvedPanel2 = new Elements.CurvedPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookListTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        BookTitle = new Elements.TextField();
        BookAuthor = new Elements.TextField();
        PublishDate = new Elements.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(25, 124, 168));
        jPanel1.setForeground(new java.awt.Color(25, 124, 168));

        curvedPanel2.setBackground(new java.awt.Color(255, 255, 255));
        curvedPanel2.setRoundBottomLeft(50);
        curvedPanel2.setRoundBottomRight(50);
        curvedPanel2.setRoundTopLeft(50);
        curvedPanel2.setRoundTopRight(50);

        BookListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Book Title", "Book Author", "Publish Date"
            }
        ));
        BookListTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(BookListTable);

        jLabel2.setFont(new java.awt.Font("AgencyFB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setText("ADD A BOOK:");

        BookTitle.setLabelText("Book Title");

        BookAuthor.setLabelText("Book Author");

        PublishDate.setLabelText("Publish Date");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout curvedPanel2Layout = new javax.swing.GroupLayout(curvedPanel2);
        curvedPanel2.setLayout(curvedPanel2Layout);
        curvedPanel2Layout.setHorizontalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(curvedPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(curvedPanel2Layout.createSequentialGroup()
                        .addComponent(BookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(BookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(PublishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        curvedPanel2Layout.setVerticalGroup(
            curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(curvedPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(curvedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PublishDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(curvedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(curvedPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String bookname = BookTitle.getText();
       String bookauthor = BookAuthor.getText();
       String publishdate = PublishDate.getText();
       
        try {
            st = con.createStatement();
        
        
           String sql = "INSERT INTO Book_List (Book_Title,Book_Author,Publish_Date)"+
                   "VALUES('"+bookname+"','"+bookauthor+"','"+publishdate+"')";

           st.execute(sql);
        }  catch (SQLException ex) {
            Logger.getLogger(BookList.class.getName()).log(Level.SEVERE, null, ex);
        } 
        finally{
            listbooks();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row2 = BookListTable.getSelectedRow();
        String selection1 = BookListTable.getModel().getValueAt(row2, 0).toString();
        String selection2 = BookListTable.getModel().getValueAt(row2, 1).toString();
       
        
       try{  
             st = con.createStatement();
            
            int row = BookListTable.getSelectedRow();
           
            String sql = "DELETE FROM Book_List WHERE Book_Title= '"+selection1+"' AND Book_Author ='"+selection2+"' ";

           st.execute(sql);   
           
            BookTitle.setText("");
            PublishDate.setText("");
            BookAuthor.setText("");
            
      }
        catch(HeadlessException | SQLException e){
                System.out.print(e);
                }
       finally{
          listbooks();
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String bookname = BookTitle.getText();
       String bookauthor = BookAuthor.getText();
       String publishdate = PublishDate.getText();
       
        int row2 = BookListTable.getSelectedRow();
        String selection1 = BookListTable.getModel().getValueAt(row2, 0).toString();
        String selection2 = BookListTable.getModel().getValueAt(row2, 1).toString();
       
        
         try{
             st = con.createStatement();
            
            String sql = "UPDATE Book_List SET Book_Title ='"+bookname+"',Book_Author= '"+bookauthor+"',Publish_Date = '"+publishdate+"'"+
                   "WHERE Book_Title= '"+selection1+"' AND Book_Author ='"+selection2+"'";

            st.execute(sql);         
            
            BookTitle.setText("");
            PublishDate.setText("");
            BookAuthor.setText("");
            
        }
        catch(HeadlessException | SQLException e){
                System.out.print(e);
        } 
         finally{
             listbooks();
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BookListTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListTableMouseClicked
        int row2 = BookListTable.getSelectedRow();
        String selection1 = BookListTable.getModel().getValueAt(row2, 0).toString();
        String selection2 = BookListTable.getModel().getValueAt(row2, 1).toString();
      
      String sql = "SELECT * FROM Book_List WHERE Book_Title= '"+selection1+"' AND Book_Author ='"+selection2+"'";
      try{
            Statement st = con.createStatement();
            
            ResultSet Rs = st.executeQuery(sql);
            
            while(Rs.next()){
                
                BookTitle.setText(Rs.getString("Book_Title"));
                BookAuthor.setText(Rs.getString("Book_Author"));
                PublishDate.setText(Rs.getString("Publish_Date"));
              
               
            }
            
      }
      catch(Exception e){
          System.out.println(e);
      }
    }//GEN-LAST:event_BookListTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Elements.TextField BookAuthor;
    private javax.swing.JTable BookListTable;
    private Elements.TextField BookTitle;
    private Elements.TextField PublishDate;
    private Elements.CurvedPanel curvedPanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
