/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Main;

import Elements.table.TableCustom;
import javax.swing.BorderFactory;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class DashBoard extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        this.invalidate();
        this.validate();
        this.repaint();
        initComponents();
        Connect();
        TableCustom.apply(jScrollPane3, TableCustom.TableType.DEFAULT);
        TableCustom.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        this.setBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI panel = (BasicInternalFrameUI) this.getUI();
        panel.setNorthPane(null);
        totalbooks();
        listbooks();
        totalissue();
        totalreturn();
        db_table_update();
    }

    Connection con;
    PreparedStatement pst;
    ResultSet Rs;
    Statement st;

    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://sql12.freesqldatabase.com/sql12711840", "sql12711840", "P4ylqiF7WZ");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void db_table_update() {
        int CC;
        try {

            pst = con.prepareStatement("SELECT * FROM issue");
            ResultSet Rs = pst.executeQuery();

            ResultSetMetaData RSMD = Rs.getMetaData();
            CC = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTable1.getModel();
            DFT.setRowCount(0);

            while (Rs.next()) {
                Vector v2 = new Vector();

                for (int ii = 1; ii <= CC; ii++) {

                    
                    
                    v2.add(Rs.getString("Grade_Level"));
                    v2.add(Rs.getString("Book_Borrowed"));
                    v2.add(Rs.getString("Date_Borrowed"));
                    v2.add(Rs.getString("Return_Date"));

                }
                DFT.addRow(v2);
            }
        } catch (Exception e) {

        }
    }
    
    public void listbooks(){
        DefaultTableModel dt =  (DefaultTableModel) jTable2.getModel();
          
         dt.setRowCount(0);
        try{ 
            st = con.createStatement();
            
            String query = "SELECT * FROM Book_List";
            
            ResultSet rs = st.executeQuery(query);
            
            while(rs.next()){
                   
                Vector v = new Vector();
              
              v.add(rs.getString("Book_Title")); 
              v.add(rs.getString("Book_Author"));
              v.add(rs.getString("Publish_Date"));

              dt.addRow(v);
            }  
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void totalbooks() {
        try {
            pst = con.prepareStatement("SELECT COUNT(*) FROM Book_List");
            Rs = pst.executeQuery();

            while (Rs.next()) {
                int icount = Rs.getInt(1);
                total_books.setText(String.valueOf(icount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void totalissue() {
        try {
            pst = con.prepareStatement("SELECT COUNT(*) FROM issue");
            Rs = pst.executeQuery();

            while (Rs.next()) {
                int icount = Rs.getInt(1);
                jLabel5.setText(String.valueOf(icount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public void totalreturn() {
        try {
            pst = con.prepareStatement("SELECT COUNT(*) FROM returnbook");
            Rs = pst.executeQuery();

            while (Rs.next()) {
                int icount = Rs.getInt(1);
                jLabel4.setText(String.valueOf(icount));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total_books = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        total_books.setFont(new java.awt.Font("AgencyFB", 1, 70)); // NOI18N
        total_books.setForeground(new java.awt.Color(255, 255, 255));
        total_books.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_books.setText("0");
        getContentPane().add(total_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 360, 100));

        jLabel4.setFont(new java.awt.Font("AgencyFB", 1, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 80, 300, 100));

        jLabel5.setFont(new java.awt.Font("AgencyFB", 1, 70)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 290, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-refresh-37.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, 40, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Book Title", "Book Author", "Publish Date"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 650, 580));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 255));
        jLabel6.setText("ISSUED BOOKS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 180, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student Number", "Book Borrowed", "Issue Date", "Return Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 660, 570));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Book List:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DBOARD.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setBounds(0, 0, 1420, 980);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       totalbooks();
        listbooks();
        totalissue();
        totalreturn();
        db_table_update();
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel total_books;
    // End of variables declaration//GEN-END:variables
}
